#!/usr/bin/env ruby
# Patches ios/Podfile (freshly generated by `expo prebuild`) so an unsigned
# `xcodebuild ... CODE_SIGNING_ALLOWED=NO` build doesn't fail with
# "requires a development team".
#
# Why this is needed: passing CODE_SIGNING_ALLOWED=NO on the xcodebuild
# command line disables signing for the main app target, but Xcode 14+
# still tries to sign individual CocoaPods targets -- especially resource
# bundles -- when building for a physical device (`-sdk iphoneos`). Without
# this patch, the build fails partway through with errors like:
#   "Signing for '<PodName>' requires a development team."
#
# This is run by codemagic.yaml right after `npx expo prebuild --platform
# ios` and before `pod install`. Safe to run locally too.

podfile_path = File.join(__dir__, '..', 'ios', 'Podfile')
podfile = File.read(podfile_path)

marker = '--- Unsigned build patch (injected by codemagic.yaml) ---'
if podfile.include?(marker)
  puts 'Podfile already patched, skipping.'
  exit 0
end

anchor = "    react_native_post_install(\n      installer,\n      config[:reactNativePath],\n      :mac_catalyst_enabled => false,\n      :ccache_enabled => ccache_enabled?(podfile_properties),\n    )"

unless podfile.include?(anchor)
  warn <<~MSG
    Could not find the expected react_native_post_install(...) block in ios/Podfile.
    Expo's generated Podfile template may have changed. Open ios/Podfile, find the
    `post_install do |installer|` block, and add the code-signing overrides from
    scripts/patch-ios-podfile.rb manually, right after the react_native_post_install
    call.
  MSG
  exit 1
end

patch = "\n\n    # #{marker}\n" \
  "    # Xcode 14+ tries to code sign every Pods target, including resource\n" \
  "    # bundles, even when building for a physical device with signing\n" \
  "    # disabled at the top level. Force it off everywhere so an unsigned\n" \
  "    # build doesn't fail with \"requires a development team\".\n" \
  "    installer.pods_project.targets.each do |target|\n" \
  "      target.build_configurations.each do |config|\n" \
  "        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'\n" \
  "        config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'\n" \
  "        config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ''\n" \
  "      end\n" \
  "    end\n" \
  "    installer.target_installation_results.pod_target_installation_results.each do |_pod_name, target_installation_result|\n" \
  "      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|\n" \
  "        resource_bundle_target.build_configurations.each do |config|\n" \
  "          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'\n" \
  "          config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'\n" \
  "        end\n" \
  "      end\n" \
  "    end\n" \
  "    # --- end unsigned build patch ---"

podfile.sub!(anchor, anchor + patch)
File.write(podfile_path, podfile)
puts 'Patched ios/Podfile to disable code signing for all Pods targets.'
